### ISSUE TITLE
cannot jump in VS Code

### ISSUE THREAD

**Issue by fleebeatles** [tqchen/ffi-navigator#36]
Hi, I installed the extension in VS Code and it turned out that it cannot jump between Python and C++ code within TVM codebase. VS Code gives the prompt "ffi_navigator is not installed. Please run "pip3 install ffi_nagivator" and reload the window" as showed below.
<img width="534" alt="WX20200226-113657@2x" src="https://user-images.githubusercontent.com/13066817/75310252-62897f80-588e-11ea-92b8-7d559f2f27dd.png">
Then I installed ffi_navigator with pip (I supposed "ffi_nagivator" was typo). However, the extension seems still not working (VS Code warns that "No definition found for ..."). 
Did I miss something to use this extension properly? Thanks for any feedback.

**Comment by VoVAllen** [comment]
It seems you have multiple python installed on your machine. And the extension in vscode extension shop hasn't be updated for a while.

**Comment by tqchen** [comment]
It would be great if you can get a repro, see some of the testcases here https://github.com/tqchen/ffi-navigator/blob/master/tests/python/test_langserver.py 

through a dummy repo location and desired target. The current version seems work fine on my side

**Comment by tqchen** [comment]
cc @comaniac

**Comment by comaniac** [comment]
The current version (extension on marketplace and the python package on PyPI) works for me on Linux and OSX.

1. Sorry for the typo. It has been fixed in upstream but not yet updated on marketplace (@tqchen should we setup a Github action workflow or similar mechanism to upload a new version automatically?)

2. As @VoVAllen mentioned, please make sure the ffi_navigator package is installed for the python you are using in VSCode. If everything works fine, you should not see the warning like "No definition found ...". Even the language server doesn't work as expected, you should just see an empty definition list shown in VSCode extension log tab instead of a popping up widget.

**Comment by tqchen** [comment]
Updated the vscode extension

**Comment by tqchen** [comment]
@fleebeatles please update the vscode extension to the lastest 0.6.1 and try again

**Comment by fleebeatles** [comment]
Thanks all for your reply.
I updated the vscode extension and it still  wouldn't work. And I tried the testcase you @tqchen posted and it worked fine. FYI, the configurations of my working enviroment is as follows. 
- The system is macos 10.14.6.
- Yes @VoVAllen I am using conda to manage the virtual env of Python and I installed ffi_navigator on both `base` env and `tvm` env (and even the system's default python env). The dependency packages of TVM are installed in `tvm` env using "conda" or "pip". However, vscode notifies that "ffi_navigator is not installed..." as before.
- In vscode, the Python interpreter is directed to the Python path of `tvm` env.
![image](https://user-images.githubusercontent.com/13066817/75442578-c26d4c80-599a-11ea-8156-f38a49eec757.png)
Besides, I found that not only the Python and C++ codes couldn't jump to the other part, but the defination of the references to tvm or vta packages couldn't be found either, as shown below. However, the TVM Python code indeed runs properly.
![image](https://user-images.githubusercontent.com/13066817/75443548-994dbb80-599c-11ea-8dc1-1739b9f4b24e.png)

Appreciate it if  someone give advice.

**Comment by VoVAllen** [comment]
Did you choose the right python interpreter at the bottom bar?

**Comment by VoVAllen** [comment]
And the configuration path for ffi navigator is 
```
{
  "ffi_navigator.pythonpath": "<your-python-path>"
}
```

**Comment by fleebeatles** [comment]
I think so @VoVAllen. Please check the followed.
![image](https://user-images.githubusercontent.com/13066817/75445466-64dbfe80-59a0-11ea-9d79-ec2d3e0110fc.png)

**Comment by comaniac** [comment]
If your VSCode cannot find tvm, it is nothing to do with ffi_navigator. This is because the `PYTHONPATH` VSCode is using does not come from your environment. The most promising way I am using is creating a file `<your-tvm-path>/.env` with the following:

```bash
PYTHONPATH=<your-tvm-path>/python:<your-tvm-path>/topi/python
```

To make this file effective, you have to either open VSCode directly in `<your-tvm-path>`, or open VSCode first and File->Open->`<your-tvm-path>`.

**Comment by fleebeatles** [comment]
@VoVAllen  Setting the right path of python interpreter for ffi-navigator works! Thanks a lot.
@comaniac You are right and thank you very much.
And want to say sorry to everyone concerned with this issue, because the [README](https://github.com/tqchen/ffi-navigator/tree/master/vscode-extension) of ffi-navigator has explained how to solve this problem and I didn't read it.
